server {
    listen 4323;
    server_name _;
    client_max_body_size 50M;
    root /home/yamiddev/auto-whatsapp/client/dist;
    index index.html;

    # Frontend - SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API al backend Express
    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy uploads
    location /uploads/ {
        proxy_pass http://127.0.0.1:3001;
    }
}
